### ISSUE TITLE
Add inital readme

### ISSUE THREAD

**Issue by arisslin** [arisslin/flattenthequeue#10]
## Description

A readme for the GitHub repositiroy is need.

What is needed?
- A short description about the project
- A setup instruction
- Description of the scripts
- Preview of the app with a picture an a link to the build / preview build

## Tasks

- [ ] Add short description
- [ ] Add script description
- [ ] Add preview section
