### ISSUE TITLE
FRONTEND: Add Content to the About Page

### ISSUE THREAD

**Issue by albert-schilling** [arisslin/flattenthequeue#13]
## Value Statement

As a **user**
I can **go to the about page and read about the project (purpose, legal terms etc.) **
in order to **know if I can trust the app or whom to contact**.

## Description (Text, Scribble, Wireframe, Design)

- On the about page, the user can read about the app's purpose as well as find the imprint, privacy policy and contact details.
- Scribble: ![Design Template](https://user-images.githubusercontent.com/59568178/81080879-8fdb5500-8ef1-11ea-94e2-dd569092106f.jpg)

## Acceptance Criteria

- [ ] The about page presents a project description, imprint, privacy policy and contact details.

## Tasks

- [ ] Research the required content (maybe use external resources to generate a legally correct imprint and privacy policy).
- [ ] Create the required components for the imprint and privacy policy (maybe create a pop up component that displays the imprint and privacy policy).
- [ ] Add styling according to the Wireframe.
- [ ] Test in mobile and desktop view in Firefox, Chrome, Safari and Edge.
- [ ] Write unit and e2e tests
- [ ] Include the components in Storybook and mdx Storybook Documentation.

## Size

Medium

**Comment by arisslin** [comment]
Reorganized folder structure and added a subfolder named pages to the folder components.

**Comment by arisslin** [comment]
Refactor lazy loading in app component

**Comment by arisslin** [comment]
Refactor footer: Deleted footer component because the footer only contains a navigations and so the code for the footer is not needed.

**Comment by arisslin** [comment]
Refactor NotFound beacuse the text is semantically no <h2>. Converted it to a <p>.
