### ISSUE TITLE
Build the Results Page

### ISSUE THREAD

**Issue by albert-schilling** [arisslin/flattenthequeue#14]
# Build the Results Page with a Mock Object and State according to the Wireframe (without backend communication or props yet)

## Value Statement

As a **user**
I can **see the details of a chosen supermarket** 
in order to **retrieve information about the supermarket's occupancy** and
I can **submit my own observation**
in order to **improve the data quality and accuracy for other users**.

## Description (Text, Scribble, Wireframe, Design)

- The page shows the supermarket's address and its current occupancy. 
- The user can check if he is at the supermarket currently.
- The user can evaluate how busy the supermarket is in his perception.
- Scribble: ![iPhone X-XS-11 Pro – 5](https://user-images.githubusercontent.com/59568178/81084994-e13a1300-8ef6-11ea-9afd-61bb2e22b94e.png)

## Acceptance Criteria

- [ ] Page shows the address and occupancy of a supermarket.
- [ ] Data comes from a mock object inside the component (no backend communication yet).
- [ ] The user can check if he is at the supermarket currently.
- [ ] The user can evaluate how busy the supermarket is in his perception via a slider.

## Tasks

- [ ] Write the necessary JSX / sub components and add state management to the existing results page component.
- [ ] Fill the initial state with mock data from inside the component for now.
- [ ] Add styling according to the wire frame.
- [ ] Test in mobile and desktop view in Firefox, Chrome, Safari and Edge.
- [ ] Write unit and e2e tests
- [ ] Include the components in Storybook and MDX Storybook Documentation.

## Size

Medium
