### ISSUE TITLE
Build the Home / Results Page

### ISSUE THREAD

**Issue by albert-schilling** [arisslin/flattenthequeue#15]
# Build the Home / Results Page with Mock Data and State according to the Wireframe (without backend communication or props yet)

## Value Statement

As a **user**
I can **type in a address** 
in order to **see a list of supermarkets sorted by occupancy**.

## Description (Text, Scribble, Wireframe, Design)

- The home page shows an input field asking for an address.
- The user can type in his or any destination address. 
- The results show a list of some mock supermarkets (use mock data for now).
- Scribble: ![iPhone X-XS-11 Pro – 4](https://user-images.githubusercontent.com/59568178/81086756-35de8d80-8ef9-11ea-9d0a-8a4288edb7e6.png)

## Acceptance Criteria

- [ ] Page shows an input field.
- [ ] After submitting an address, the page shows a list of random supermarkets sorted by occupancy.
- [ ] Data comes from a mock object inside the component (no backend communication yet).

## Tasks

- [ ] Write the necessary JSX / sub components and add state management to the existing home page component.
- [ ] Fill the initial state with mock data from inside the component for now.
- [ ] Add styling according to the wire frame (maybe, add the svg icons to a separate folder and then import them).
- [ ] Test in mobile and desktop view in Firefox, Chrome, Safari and Edge.
- [ ] Write unit and e2e tests
- [ ] Include the components in Storybook and MDX Storybook Documentation.

## Size

Medium
