### ISSUE TITLE
Squash and rebase at merging.

### ISSUE THREAD

**Issue by arisslin** [arisslin/flattenthequeue#19]
## Question

Is it possible to ajdust the repo that it does autimatically a sqash and a rebase when merging a feature branch?

## Tasks
- [x] Inform about squash and rebase mergin
- [x] Check if it is usefull for this repo
- [x] If it is usefull and possible configure it for this repo

**Comment by arisslin** [comment]
Ressources:
https://git-scm.com/book/de/v2/Git-Branching-Rebasing
