### ISSUE TITLE
REFACTOR: Introduce TypeScript for long-term app stability

### ISSUE THREAD

**Issue by albert-schilling** [arisslin/flattenthequeue#37]
## Value Statement

Introduce TypeScript to improve code quality and long-term maintainability, thus provide a more stable app for users.

## Description (Text, Scribble, Wireframe, Design)

Introduce TypeScript into the CRA project with all required packages and configurations.

## Acceptance Criterias

- [x] All components and tests are refactored into TS / TSX files and compile without any errors or warnings.

## Tasks

- [x] Install and configure packages.
- [x] Refactor components and tests.
