### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by arisslin** [arisslin/flattenthequeue#7]
## Description

An initial project setup is need for start with programming.
At first this will be done for the frontend. 
Backend will follow in a _seperate issue_.

Needed technologies and tools:
- npm
- create-react-app
- prettier
- eslint
- eslint-plugin-prettier
- eslint-plugin-react
- eslint-config-prettier
- eslint-config-react-app
- husky

Husky should rund on **pre-commit** and **pre-push**:
- **pre-commit**:
  - lint react, js, jsx
  - fix react, js, jsx
  - format with prettier
- **pre-push**:
  - lint react, js, jsx
  - fix react, js, jsx
  - format with prettier

## Tasks
- [x] Install npm
- [x] Configure npm
- [x] Add gitignore
- [x] Create npm scripts
- [x] Install create-react-app
- [x] Install prettier
- [x] Install eslint
- [x] Install eslint-plugin-prettier
- [x] Install eslint-plugin-react
- [x] Install eslint-config-prettier
- [x] Install eslint-config-react-app
- [x] Install husky
- [x] Configure create-react-app
- [x] Configure prettier
- [x] Configure eslint
- [x] Configure husky
- [x] Install styled components

## Acceptance criterias

- [x] styled components works

**pre-commit**:
- [x] lint react, js, jsx
- [x] fix react, js, jsx
- [x] format with prettier

**pre-push**:
- [x] lint react, js, jsx
