### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by arisslin** [arisslin/flattenthequeue#9]
## Description

Storybook is needed for develop and documentation of react components.

## Tasks

- [x] Install storybook
- [x] Configure storybook
- [ ] ~~use storyshots addon to keep stories in sync with the source~~
- [x] Add npm scripts to package.json
- [x] Update REAMDE.md chapter _Tech Stack & Toolchain_ about new installed tech
- [x] Update README.md chapter _Available Scripts_ about the new npm scripts

**Comment by arisslin** [comment]
Do you have a good ressource?

**Comment by jamarob** [comment]
The official docs are pretty good
https://storybook.js.org/docs/formats/mdx-syntax/
https://github.com/storybookjs/storybook/tree/master/addons/docs
https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core

I can take care of installation and configuration

**Comment by jamarob** [comment]
Generation of snapshots from mdx files will get it's own ticket.
